---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.xlarge
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-9883c6f2

suites:
  - name: agent
    driver:
      tags:
        Name: et_monitoring-agent-ubuntu-1404
    run_list:
      - recipe[et_monitoring::agent]
    attributes:
      newrelic:
        server_monitor_agent:
          service_notify_action: nothing
          service_actions:
            - enable
