---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.xlarge
  tags:
    Env: public
    Type: test
    Operator: <%= ENV['USER'] %>

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: agent
    driver:
      tags:
        Name: et_monitoring-agent-ubuntu-1404
    run_list:
      - recipe[et_monitoring::agent]
    attributes:
      newrelic:
        server_monitor_agent:
          service_notify_action: nothing
          service_actions:
            - enable
      et_monitoring:
        datadog:
          kafka:
            instances:
              - host: localhost
                port: 19092
                java_bin_path: /usr/bin/java
                tags:
                  - kafka:dev
                  - env:dev
