---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: agent
    run_list:
      - recipe[et_monitoring::agent]
    attributes:
      newrelic:
        server_monitor_agent:
          service_notify_action: nothing
          service_actions:
            - enable
